name: Daily News Update

on:
  schedule:
    - cron: '0 0 * * *' # Otomatis jalan setiap jam 12 malam (UTC)
  workflow_dispatch: # Tombol manual agar bisa kamu tes kapan saja
  
# TAMBAHKAN BARIS INI:
permissions:
  contents: write


jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib beautifulsoup4 requests

      - name: Run Scraper
        run: python scripts/scrapper.py # <--- PASTIKAN NAMA FILE PYTHON KAMU BENAR

       - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Ambil perubahan terbaru dari cloud untuk menghindari konflik
          git pull origin main --rebase
          
          git add tren_berita.png
          
          # Hanya commit jika ada perubahan agar tidak error
          git commit -m "Automated update: Tren Berita Terbaru $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          
          git push origin main

