name: Daily News and Crypto Update

on:
  schedule:
    - cron: '0 * * * *' # Berjalan tiap 1 jam
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib beautifulsoup4 requests lxml

      - name: Run Scraper News
        run: python scripts/scrapper.py

      - name: Run Crypto Analyzer
        run: python scripts/crypto_analyzer.py

      - name: Commit and Push All Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Menarik perubahan terbaru agar tidak bentrok
          git pull origin main --rebase
          
          # Menambahkan semua file hasil produksi script
          git add tren_berita.png top_keyword.txt crypto_trend.png crypto_status.txt
          
          # Commit hanya jika ada perubahan
          git commit -m "Automated update: News, Keywords, and Crypto Data" || echo "No changes to commit"
          git push origin main
