name: Daily News Update

on:
  schedule:
    - cron: '0 * * * *' # Saya ubah ke tiap 1 jam agar lebih hemat menit namun tetap live
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib beautifulsoup4 requests lxml

      - name: Run Scraper
        run: python scripts/scrapper.py
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Tambahkan kedua file ini
          git add tren_berita.png top_keyword.txt
          
          git stash
          git pull origin main --rebase
          git stash pop || echo "No stash"
          
          git add tren_berita.png top_keyword.txt
          git commit -m "Automated update: News & Keywords" || echo "No changes"
          git push origin main
      # - name: Commit and Push
      #   run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
          
      #     # 1. Tandai file yang berubah dulu
      #     git add tren_berita.png top_keyword.txt
          
      #     # 2. Lakukan stash sementara agar pull rebase tidak protes
      #     git stash
      #     git pull origin main --rebase
      #     git stash pop || echo "No stash to pop"
          
      #     # 3. Commit dan Push
      #     git add tren_berita.png
      #     git commit -m "Automated update: Tren Berita Terbaru $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
      #     git push origin main

